config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :fluxes

  devise_for :users
  resources :widgets

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base

  belongs_to :flux
  
end

app/models/flux.rb
class Flux < ActiveRecord::Base

  has_many :articles, dependent: :destroy
  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :fluxes, dependent: :destroy
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show]

  respond_to :html

  def show
    respond_with(@article)
  end

  private
    def set_article
      @article = Article.find(params[:id])
      if @article.views.nil?
        @article.views = 0
      end
      @article.views += 1;
      @article.save
    end

    def article_params
      params.require(:article).permit(:title, :content, :pub_date, :flux, :image_url)
    end
end

app/controllers/fluxes_controller.rb
require 'open-uri'

class FluxesController < ApplicationController
  before_filter :check_user
  before_action :set_flux, :authenticate_user!, only: [:show, :update, :destroy]

  respond_to :html

  def index
    @fluxes = Flux.where(:user => current_user).paginate(:page => params[:page], :per_page => 5)
    @articles = Article.order(pub_date: :desc).limit(9)
    respond_with(@fluxes, @articles)
  end

  def show
    respond_with(@flux)
  end

  def new
    @flux = Flux.new
    respond_with(@flux)
  end

  def create
    @flux = Flux.new(flux_params)
    rss = SimpleRSS.parse open(@flux.url)
    @flux.title = rss.channel.title
    @flux.user = current_user
    @flux.save
    respond_with(@flux)
  end

  def update
    @flux.update(flux_params)
    respond_with(@flux)
  end

  def destroy
    @flux.destroy
    respond_with(@flux)
  end

  private
    def set_flux
      @flux = Flux.find(params[:id])

      if(@flux.user != current_user)
        return
      end

      if @flux == nil
        return
      end

      if @flux.fetched_at == nil || @flux.fetched_at < (Time.new - 60*15)
        # Suppression de tous les articles
        @flux.articles.delete_all

        # On recharge la liste des flux depuis le site
        SimpleRSS.item_tags << :'enclosure#url'
        rss = SimpleRSS.parse open(@flux.url)
        coder = HTMLEntities.new
        rss.items.each {|article|
          title = article.title.force_encoding('UTF-8')
          description = coder.decode(article.description.force_encoding('UTF-8'))
          @flux.articles.create(title: title, content: description, url: article.link, pub_date: article.pubDate, image_url: article.enclosure_url, views: 0)
          }

        @flux.fetched_at = Time.new
        @flux.save
      end
    end

    def check_user
        redirect_to url_for :controller => 'devise/sessions', :action => 'new' and return unless user_signed_in?
    end

    def flux_params
      params.require(:flux).permit(:url)
    end
end

#:title

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  respond_to :html

  # GET /welcome
  def index
    @articles = Article.order(views: :desc).limit(9)
    respond_with(@articles)
  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render :show, status: :created, location: @widget }
      else
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
        format.json { render :show, status: :ok, location: @widget }
      else
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/fluxes_helper.rb
module FluxesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Retour vers ' + @article.flux.title, flux_path(@article.flux) %>

<p>
  <h1><%= @article.title %></h1>
</p>

<p>
  Publié le :
  <%= @article.pub_date %>
  - Nombre de vues : <%= @article.views %>
</p>

<p>
<img src="<%= @article.image_url %>">
</p>

<p>
  <%= link_to 'Voir sur le site', @article.url %>
</p>

<p>
  <%= @article.content.html_safe %>
</p>

app/views/fluxes/_form.html.erb
<%= form_for(@flux) do |f| %>
  <% if @flux.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flux.errors.count, "error") %> prohibited this flux from being saved:</h2>

      <ul>
      <% @flux.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :titre %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fluxes/index.html.erb
<h1>Gestion des flux</h1>

<p>
<%= link_to 'Ajouer un flux', new_flux_path, :class => "btn btn-default" %>
</p>

<table class="table">
  <thead>
    <tr>
      <th>Url</th>
      <th>Titre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fluxes.each do |flux| %>
      <tr>
        <td><%= flux.url %></td>
        <td><%= flux.title %></td>
        <td><%= link_to 'Afficher', flux %></td>
        <td> - </td>
        <td><%= link_to 'Supprimer', flux, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= will_paginate @fluxes %>

<h1>Derniers articles</h1>

<div class="row">

<% @articles.each do |article| %>

  <div class="col-sm-6 col-md-4 extrait">
    <div class="thumbnail">
      <a href="<%= article_path(:id => article.id) %>">
      <% if article.image_url != nil %>
        <img src="<%= article.image_url %>" alt="<%= article.title %>">
      <% end %>
      <div class="caption">
        <p class="popularity"><%= article.views %></p>
        <h4><%= article.title %></h4>
      </div>
      </a>
    </div>
  </div>

<% end %>
</div>

app/views/fluxes/new.html.erb
<h1>Nouveau flux</h1>

<%#= render 'form' %>
<%= form_for @flux, url: {action: "create"} do |f| %>
<%= f.text_field :url %>
<%= f.submit "Nouveau" %>
<% end %>

<%= link_to 'Retour', fluxes_path %>

app/views/fluxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'Retour', fluxes_path %>
</p>

<p>

</p>

<h1><%= @flux.title %></h1>

<p>Mis à jour le <%= @flux.fetched_at.to_s %> - <%= link_to @flux.url, @flux.url %></p>

<div class="row">

<% @flux.articles.each do |article| %>

  <div class="col-sm-6 col-md-4 extrait">
    <div class="thumbnail">
      <a href="<%= article_path(:id => article.id) %>">
        <% if article.image_url != nil %>
          <img src="<%= article.image_url %>" alt="<%= article.title %>">
        <% end %>
        <div class="caption">
        <p class="popularity"><%= article.views %></p>
        <h4><%= article.title %></h4>
      </div>
      </a>
    </div>
  </div>

<% end %>

</div>

<%= link_to 'Supprimer', @flux, method: :delete, :class => "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AiRSS</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <ul class="nav navbar-nav">
                  <% if  !user_signed_in? %>
                    <li>
                        <%= link_to 'AiRSS',new_user_session_path %>
                    </li>
                  <% else %>
                  <li>
                      <%= link_to 'AiRSS',root_path%>
                  </li>
                  <% end %>
                </ul>

            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                  <% if  !user_signed_in? %>
                  <li>
                    <%= link_to 'Inscription',new_user_registration_path %>
                  </li>
                  <% else %>
                  <li>
                      <%= link_to 'Profil', edit_user_registration_path %>
                  </li>
                  <% end %>
                  <% if  !user_signed_in? %>
                    <li>
                        <%= link_to 'Connexion',new_user_session_path %>
                    </li>
                  <% else %>
                    <li>
                        <%= link_to 'Déconnexion', destroy_user_session_path, :method => :delete %>
                    </li>
                  <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <% if current_page?('/') %>
    <!-- Half Page Image Background Carousel Header -->
    <header id="myCarousel" class="carousel slide">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for Slides -->
        <div class="carousel-inner">
            <div class="item active">
                <!-- Set the first background image using inline CSS below. -->
                <div class="fill" style="background-image:url('http://www.atelier-android.com/wp-content/uploads/2011/11/flux-RSS1.jpg');"></div>
                <div class="carousel-caption">
                </div>
            </div>
            <div class="item">
                <!-- Set the second background image using inline CSS below. -->
                <div class="fill" style="background-image:url('http://www.keepitsimple.fr/wp-content/uploads/2015/01/flux-rss.jpg');"></div>
                <div class="carousel-caption">
                </div>
            </div>
            <div class="item">
                <!-- Set the third background image using inline CSS below. -->
                <div class="fill" style="background-image:url('http://www.icone-png.com/png/52/51518.png');"></div>
                <div class="carousel-caption">
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="icon-prev"></span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="icon-next"></span>
        </a>

    </header>
    <% else %>
    <% end %>


    <!-- Page Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <%= yield %>
            </div>
        </div>

        <hr>

        <!-- Footer -->
      <footer>
            <div class="row">
                <div class="col-lg-9">
                    <p>Copyright &copy; AiRSS 2015</p>
                </div>
                <div class="col-lg-3">
                      <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="bottom" style = "float: right">
                      <input type="hidden" name="cmd" value="_donations">
                      <input type="hidden" name="business" value="airss.mail@gmail.com">
                      <input type="hidden" name="lc" value="FR">
                      <input type="hidden" name="item_name" value="AIRSS">
                      <input type="hidden" name="no_note" value="0">
                      <input type="hidden" name="currency_code" value="EUR">
                      <input type="hidden" name="bn" value="PP-DonationsBF:btn_donateCC_LG.gif:NonHostedGuest">
                      <input type="image" src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - la solution de paiement en ligne la plus simple et la plus sécurisée !">
                      <img alt="" border="0" src="https://www.paypalobjects.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
                    </form>

                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>


</html>

app/views/welcome/index.erb
<h1>Hub de la communauté</h1>

<% if  user_signed_in? %>
<p style="text-align: center; margin: 30px;">
  <%= link_to 'Accéder à mes flux', fluxes_path, :class => 'btn btn-default' %>
</p>
<% end %>

<div class="row">

<% @articles.each do |article| %>

  <div class="col-sm-6 col-md-4 extrait">
    <div class="thumbnail">
      <a href="<%= article_path(:id => article.id) %>">
        <% if article.image_url != nil %>
          <img src="<%= article.image_url %>" alt="<%= article.title %>">
        <% end %>      <div class="caption">
        <p class="popularity"><%= article.views %></p>
        <h4><%= article.title %></h4>
      </div>
      </a>
    </div>
  </div>

<% end %>

</div>

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.stock %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @widget.stock %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>